scene:
  shapes:
    - name: sphere
      radius: 1
      center: [0, 0, -1.5]
      color: [1.0, 0.0, 0.0]
    # - name: sphere
    #   radius: 0.3
    #   center: [0.5, 0.5, -3]
    #   color: [1.0, 0.0, 0.0]


image: 
  filename: "tmp_output/image.ppm"
  xres: 720
  yres: 480

camera:
  fov: 90
  roll: 0
  direction: [0, 0, -1] # direction camera points towards
  location: [0, 0, 0]
