scene:
  shapes:
    - name: sphere
      radius: 1
      center: [0, 0, -1.5]
      color: [1.0, 0.0, 0.0]
    - name: sphere
      radius: 0.5
      center: [0.9, 0.9, 4]
      color: [0.0, 0.0, 1.0]
    - name: sphere
      radius: 0.2
      center: [-1.6, 1.2, 0.5]
      color: [0.0, 1.0, 0.0]
    - name: sphere
      radius: 4
      center: [0, 0, -10]
      color: [0.0, 0.0, 0.40]
    - name: sphere
      radius: 0.4
      center: [-2, -2, 0.5]
      color: [0.2, 0.8, 0.2]
    - name: sphere
      radius: 0.3
      center: [1.6, -1.2, 0.5]
      color: [0.8, 0.4, 0.56]
  lights:
    - name: directional
      color: [1, 1, 1]
      intensity: 1.0
      direction: [0, 0, -22]
      location: [0, 0, 22]


image: 
  filename: "tmp_output/image.ppm"
  xres: 640
  yres: 360

camera:
  fov: 20
  roll: 0
  direction: [0, 0, -20] # direction camera points towards
  location: [0, 0, 20]

performance:
  antialiasing_samples: 4
  multiprocessing: true
