scene:
  shapes:
    - name: sphere
      radius: 0.2
      center: [0, 0, -1]
      color: [1.0, 0.0, 0.0]
    - name: sphere
      radius: 0.3
      center: [0.5, 0.5, -1]
      color: [1.0, 0.0, 0.0]


image: 
  filename: "tmp_output/image.ppm"
  xres: 720
  yres: 480
