scene:
  shapes:
    - name: sphere
      radius: 1
      center: [0, 0, -1.5]
      color: [1.0, 0.0, 0.0]
    - name: sphere
      radius: 0.5
      center: [1, 1, 0.5]
      color: [0.0, 0.0, 1.0]


image: 
  filename: "tmp_output/image.ppm"
  xres: 1920
  yres: 1080

camera:
  fov: 40
  roll: 0
  direction: [0, 0, -1] # direction camera points towards
  location: [0, 0, 5]

performance:
  antialiasing_samples: 9
  multiprocessing: true
